// <auto-generated />
using System;
using Bookshop.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookshop.DAL.Migrations;

[DbContext(typeof(BookshopDbContext))]
partial class BookshopDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

        modelBuilder.Entity("Bookshop.DAL.Entities.Author", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ImageUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Authors");
            });

        modelBuilder.Entity("Bookshop.DAL.Entities.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("AuthorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("BookType")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("TEXT");

                b.Property<string>("ImageUrl")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Price")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("PublishDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AuthorId");

                b.ToTable("Books");
            });

        modelBuilder.Entity("Bookshop.DAL.Entities.Book", b =>
            {
                b.HasOne("Bookshop.DAL.Entities.Author", "Author")
                    .WithMany("Books")
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Author");
            });

        modelBuilder.Entity("Bookshop.DAL.Entities.Author", b =>
            {
                b.Navigation("Books");
            });
#pragma warning restore 612, 618
    }
}
